/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as votingSol from './Voting.sol/index.js';
export type { votingSol };
export * as factories from './factories/index.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { Voting } from './Voting.sol/Voting.js';
export { Voting__factory } from './factories/Voting.sol/Voting__factory.js';